apiVersion: v1
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
    <title>uat</title>
    </head>
    <body style="background-color:orange;">

    <h1>uat</h1>

    </body>
    </html>
kind: ConfigMap
metadata:
  name: kargo-demo-content
