apiVersion: v1
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
    <title>test</title>
    </head>
    <body style="background-color:red;">

    <h1>test</h1>

    </body>
    </html>
kind: ConfigMap
metadata:
  name: kargo-demo-content
